# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='insitution',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='visibility',
            new_name='post_status',
        ),
    ]
