# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160131_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='type',
            new_name='post_type',
        ),
        migrations.AlterField(
            model_name='resource',
            name='post_status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft'), ('trash', 'Trash')], max_length=25),
        ),
    ]
