# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160201_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
