# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160203_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='event_date',
            new_name='event_time',
        ),
    ]
