# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160203_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='openphoto',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='openphoto',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='openphoto',
            name='post_status',
            field=models.CharField(blank=True, choices=[('publish', 'Publish'), ('draft', 'Draft'), ('trash', 'Trash')], max_length=25),
        ),
        migrations.AddField(
            model_name='openphoto',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='openphoto',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
