# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160207_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openphoto',
            name='content',
        ),
    ]
