# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_openphoto_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openphoto',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
