# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20160207_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='openphoto',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
