# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_openphoto_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='openphoto',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='openphoto',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
