# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20160208_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='openphoto',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='resource',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
