# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20160226_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='archive_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='archive_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='event_directions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='event_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='institution_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='event_type',
            field=models.CharField(blank=True, choices=[('conference/forum/discussion', 'Conference/forum/discussion'), ('conference/seminar', 'Conference/seminar'), ('workshop', 'Workshop'), ('forum/panel/discussion', 'Forum/panel/discussion'), ('other_local', 'other_local'), ('local', 'local'), ('webinar', 'Webinar'), ('discussion', 'Online Discussion'), ('other_online', 'Other - Online')], max_length=255),
        ),
    ]
