# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20160813_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(to='web.Category'),
        ),
    ]
