# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20160815_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='event_other_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
