# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_resource_event_other_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
