# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20160818_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='raw_post',
            field=models.TextField(blank=True),
        ),
    ]
