# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_resource_raw_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='event_facilitator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
