# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20170124_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='screenshot_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
