# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20170209_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
