# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_resource_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, default=2017, null=True),
        ),
    ]
