# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-02 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_resource_linkwebroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='opentags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='event_type',
            field=models.CharField(blank=True, choices=[('conference/forum/discussion', 'Conference/forum/discussion'), ('conference/seminar', 'Conference/seminar'), ('workshop', 'Workshop'), ('forum/panel/discussion', 'Forum/panel/discussion'), ('other_local', 'other_local'), ('local', 'local'), ('webinar', 'Webinar'), ('discussion', 'Online Discussion'), ('other_online', 'Other - Online'), ('online', 'Online Event')], max_length=255),
        ),
    ]
