# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 14:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20180220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='opentags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, size=None),
        ),
    ]
