# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20180220_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='oeaward',
            field=models.BooleanField(default=False),
        ),
    ]
