# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_resource_oeaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openphoto',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='resource',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='OpenPhoto',
        ),
    ]
