# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20180808_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
