# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_auto_20180827_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource',
            new_name='image',
        ),
    ]
