# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_auto_20180827_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ResourceImage'),
        ),
    ]
