# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20180827_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
