# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-12 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_auto_20190215_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
