# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20191212_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, default=2021, null=True),
        ),
    ]
