# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0056_auto_20210107_0806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conference/forum/discussion", "Conference/forum/discussion"),
                    ("conference/seminar", "Conference/seminar"),
                    ("workshop", "Workshop"),
                    ("forum/panel/discussion", "Forum/panel/discussion"),
                    ("other_local", "other_local"),
                    ("local", "local"),
                    ("webinar", "Webinar"),
                    ("discussion", "Online Discussion"),
                    ("other_online", "Other - Online"),
                    ("online", "Online Event"),
                    ("anytime", "Anytime Event"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
